### ISSUE TITLE
Error: Program type already present: com.vidyo.LmiDeviceManager.LmiAudioPlaybackDevice

### ISSUE THREAD

**Issue by srijith1979** [Vidyo/vidyoplatform-custom-connector-android#1]
Hi Team,

The app which I work on references two libraries and each of these libraries includes com.vidyo.LmiDeviceManager

I am running into the above error when I try to build my android app.

Your help on this will be greatly appreciated. Please find the below screenshot for reference. Thanks.

<img width="1132" alt="Screen Shot 2019-12-03 at 5 25 44 PM" src="https://user-images.githubusercontent.com/16881321/70098634-3abdaf00-15f2-11ea-88ba-6f135fc24b6a.png">

**Comment by tmelko-vidyo** [comment]
It's not possible to integrate 2 VidyoClient libraries into one project. 
Java JNI layer will conflict.
